coverage:
  precision: 2
  round: down
  range: "100...100"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

status:
  project:
    default:
      target: 100%
      threshold: 0%
      if_ci_failed: error
  patch:
    default:
      target: 100%
      threshold: 0%
      if_ci_failed: error
